### ISSUE TITLE
Things that are not there

### ISSUE THREAD

**Issue by shaharbukra** [anttikajanus/DSE2017-building-apps-ArcGISRuntime-dotnet#1]
-  in the project you use toolkit beta3, there is only beta2 public for the rest of us :)

/src/BuildingAppsDemo/BuildingAppsDemo.csproj
 <PackageReference Include="Esri.ArcGISRuntime.Toolkit.UWP">
      <Version>100.1.0-beta3.gffe1b18783</Version>
    </PackageReference>

- you used ToggleSwitchFillOn which doesn't exists in the project also

And again,
Thanks!! :1st_place_medal:

**Comment by anttikajanus** [comment]
I'll fix the readme to contain the information to setup the toolkit reference tomorrow.  Sounds like that there are some other requirements as well and I could clean the demo up as well.

**Comment by anttikajanus** [comment]
Fixed.
