### ISSUE TITLE
Why the curly brackets?

### ISSUE THREAD

**Issue by pekkah** [anttikajanus/DSE2017-building-apps-ArcGISRuntime-dotnet#2]
https://github.com/anttikajanus/DSE2017-building-apps-ArcGISRuntime-dotnet/blob/b94cb1f35509e81785f9900d60fbff79460854df/src/BuildingAppsDemo/MapViewModel.cs#L101

**Comment by anttikajanus** [comment]
It was missing else for some reason. Anyways, fixed.
